In [16]:
import numpy as np
a=np.eye(2)

c=np.array([[0,1],[0,2]])
b=c

In [9]:
a


array([[1., 0.],
       [0., 1.]])

In [10]:
b

array([1., 1.])

In [11]:
c

array([[0, 1],
       [0, 2]])

In [12]:
a*b

array([[1., 0.],
       [0., 1.]])

In [13]:
a.dot(b)

array([1., 1.])

In [17]:
b*c

array([[0, 1],
       [0, 4]])

In [18]:
b.dot(c)

array([[0, 2],
       [0, 4]])

C:\Users\arpit agrawal\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([[      -inf, 0.        ],
       [      -inf, 0.69314718]])